### ISSUE TITLE
typo on articulated_system::get_frame_angular_velocity pybind11 register

### ISSUE THREAD

**Issue by dytan** [robotlearn/raisimpy#10]
Hi, guys. Found misspelling on [articulated_system.get_frame_angular_velocity] (https://github.com/robotlearn/raisimpy/blob/master/src/articulated_system.cpp#L1192) pybind registration.
``` cpp
.def("get_frame_angular_velocity", [](raisim::ArticulatedSystem &self, size_t frame_id) {
            Vec<3> vec;
            self.getFrameVelocity(frame_id, vec);
            return convert_vec_to_np(vec);
        }, R"mydelimiter(
        Get the frame angular velocity expressed in the Cartesian world frame.
```
Doubt the right call should be __'self.getFrameAngularVelocity(frame_id, vec);'__

**Comment by jhwangbo** [comment]
Thank you for the report. I just merged the correction PR
