### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sashank-tirumala** [robotlearn/raisimpy#24]
Hey I tried installing raisimpy with python3.5 on my Ubuntu 18.0 system. The make keeps failing with this error, Any idea how to fix this?
[ 14%] Building CXX object CMakeFiles/raisimpy.dir/src/articulated_system.cpp.o
[ 14%] Building CXX object CMakeFiles/raisimpy.dir/src/math.cpp.o
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp: In function ‘void init_articulated_system(pybind11::module&)’:
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: error: no match for call to ‘(const pybind11::detail::overload_cast_impl<long unsigned int>) (<unresolved overloaded function type>, const std::integral_constant<bool, true>&)’
 verload_cast<size_t>(&raisim::ArticulatedSystem::getMass, py::const_), R"mydelimiter(
                                                                     ^
In file included from /home/sashank/anaconda3/include/python3.7m/pybind11/pytypes.h:12:0,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/cast.h:13,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/attr.h:13,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/pybind11.h:44,
                 from /home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:25:
/home/sashank/anaconda3/include/python3.7m/pybind11/detail/common.h:729:20: note: candidate: template<class Return> constexpr decltype (pf) pybind11::detail::overload_cast_impl<Args>::operator()(Return (*)(Args ...)) const [with Return = Return; Args = {long unsigned int}]
     constexpr auto operator()(Return (*pf)(Args...)) const noexcept
                    ^~~~~~~~
/home/sashank/anaconda3/include/python3.7m/pybind11/detail/common.h:729:20: note:   template argument deduction/substitution failed:
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   mismatched types ‘Return (*)(long unsigned int)’ and ‘double (raisim::ArticulatedSystem::*)(size_t) {aka double (raisim::ArticulatedSystem::*)(long unsigned int)}’
 verload_cast<size_t>(&raisim::ArticulatedSystem::getMass, py::const_), R"mydelimiter(
                                                                     ^
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   mismatched types ‘Return (*)(long unsigned int)’ and ‘std::vector<double>& (raisim::ArticulatedSystem::*)()’
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   could not resolve address from overloaded function ‘& raisim::ArticulatedSystem::getMass’
In file included from /home/sashank/anaconda3/include/python3.7m/pybind11/pytypes.h:12:0,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/cast.h:13,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/attr.h:13,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/pybind11.h:44,
                 from /home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:25:
/home/sashank/anaconda3/include/python3.7m/pybind11/detail/common.h:733:20: note: candidate: template<class Return, class Class> constexpr decltype (pmf) pybind11::detail::overload_cast_impl<Args>::operator()(Return (Class::*)(Args ...), std::false_type) const [with Return = Return; Class = Class; Args = {long unsigned int}]
     constexpr auto operator()(Return (Class::*pmf)(Args...), std::false_type = {}) const noexcept
                    ^~~~~~~~
/home/sashank/anaconda3/include/python3.7m/pybind11/detail/common.h:733:20: note:   template argument deduction/substitution failed:
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   candidate expects 2 arguments, 1 provided
 verload_cast<size_t>(&raisim::ArticulatedSystem::getMass, py::const_), R"mydelimiter(
                                                                     ^
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   cannot convert ‘pybind11::const_’ (type ‘const std::integral_constant<bool, true>’) to type ‘std::false_type {aka std::integral_constant<bool, false>}’
In file included from /home/sashank/anaconda3/include/python3.7m/pybind11/pytypes.h:12:0,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/cast.h:13,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/attr.h:13,
                 from /home/sashank/anaconda3/include/python3.7m/pybind11/pybind11.h:44,
                 from /home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:25:
/home/sashank/anaconda3/include/python3.7m/pybind11/detail/common.h:737:20: note: candidate: template<class Return, class Class> constexpr decltype (pmf) pybind11::detail::overload_cast_impl<Args>::operator()(Return (Class::*)(Args ...) const, std::true_type) const [with Return = Return; Class = Class; Args = {long unsigned int}]
     constexpr auto operator()(Return (Class::*pmf)(Args...) const, std::true_type) const noexcept
                    ^~~~~~~~
/home/sashank/anaconda3/include/python3.7m/pybind11/detail/common.h:737:20: note:   template argument deduction/substitution failed:
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   types ‘Return (Class::)(long unsigned int) const’ and ‘double (raisim::ArticulatedSystem::)(size_t) {aka double (raisim::ArticulatedSystem::)(long unsigned int)}’ have incompatible cv-qualifiers
 verload_cast<size_t>(&raisim::ArticulatedSystem::getMass, py::const_), R"mydelimiter(
                                                                     ^
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   types ‘Return (Class::)(long unsigned int) const’ and ‘std::vector<double>& (raisim::ArticulatedSystem::)()’ have incompatible cv-qualifiers
/home/sashank/raisim_ws/raisimpy/src/articulated_system.cpp:1355:99: note:   could not resolve address from overloaded function ‘& raisim::ArticulatedSystem::getMass’
[ 21%] Building CXX object CMakeFiles/raisimpy.dir/src/object.cpp.o
CMakeFiles/raisimpy.dir/build.make:62: recipe for target 'CMakeFiles/raisimpy.dir/src/articulated_system.cpp.o' failed
make[2]: *** [CMakeFiles/raisimpy.dir/src/articulated_system.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/raisimpy.dir/all' failed
make[1]: *** [CMakeFiles/raisimpy.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhwangbo** [comment]
which pybind11 version do you have? I recommend v2.4.3. I had issues with the pybind and I suspect that it can be a pybind11 issue

I just tested on my machine and it compiles fine.

**Comment by sashank-tirumala** [comment]
Yeah I checkout out to version 2.4.3. I suspect it might be my python version (3.7) so I created a virtual environment with anaconda with python version 3.5. Raisimpy detected python in that virtual env 3.5 however pybind11 does not detect that python version
 cmake .. -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD -DPYBIND11_TEST=OFF
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /home/sashank/anaconda3/bin/python3.7 (found version "3.7.4") 
-- Found PythonLibs: /home/sashank/anaconda3/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.4.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sashank/raisim_ws/pybind11/build

Any idea how I can make pyBind detect python version 3.5 which I was using in my virtual env. It may also not be a python issue, which python version are you using?

**Comment by jhwangbo** [comment]
I test it with 3.5 and 3.6. I didn't know there is an issue in 3.7. When you build raisimpy, you can specify the python version

**Comment by lok-i** [comment]
Hi there,
I have installed raisimLib,raisimOgre,pybind11(2.4.3) as instructed. The installation of raisimPy is successful as well (without any errors). But when I run a python script raisimpy is not detected as a module. I am currently using python 3.6.9.I suspect there is some error in the PYTHONPATH variable(though I have copy-pasted the exact line from the readme into my bashrc).

           export PYTHONPATH=$PYTHONPATH:$LOCAL_BUILD/lib

Yet my python is nowhere detecting the raisimPy module. It would be helpful if I get the exact commands to be pasted in the bashrc or the real fix for the problem if there is anything else.

Thanks!

**Comment by jhwangbo** [comment]
Did you export LOCAL_BUILD before you export the python path? If you didnt, then you can also specify the actual path instead, e.g.
`PYTHONPATH=$PYTHONPATH:/usr/sash/raisim_local_build/lib`

**Comment by lok-i** [comment]
> Did you export LOCAL_BUILD before you export the python path? If you didnt, then you can also specify the actual path instead, e.g.
> `PYTHONPATH=$PYTHONPATH:/usr/sash/raisim_local_build/lib`

Yes, I have, and these are my exact lines in bashrc:-

export LOCAL_BUILD="/home/lok/Raisim/raisim_build"
export PYTHONPATH=$PYTHONPATH:$LOCAL_BUILD/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LOCAL_BUILD/lib

Yet python is not able to detect raisimpy as a installed module.

**Comment by lok-i** [comment]
> Did you export LOCAL_BUILD before you export the python path? If you didnt, then you can also specify the actual path instead, e.g.
> `PYTHONPATH=$PYTHONPATH:/usr/sash/raisim_local_build/lib`

Yes I have, and these are the exact line in my baskrc
export LOCAL_BUILD="/home/lok/Raisim/raisim_build"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LOCAL_BUILD/lib
export PYTHONPATH=$PYTHONPATH:$LOCAL_BUILD/lib

Yet python is not able to detect raisimpy as an installed module.

**Comment by lok-i** [comment]
> Did you export LOCAL_BUILD before you export the python path? If you didnt, then you can also specify the actual path instead, e.g.
> `PYTHONPATH=$PYTHONPATH:/usr/sash/raisim_local_build/lib`

Hi there,
After installation of raisimpy, can we build and run the python code directly from the python interpreter or can it only be built as a cmake project like with any C++ source file as in exampes of raisimLib ?
Thanks !

**Comment by jhwangbo** [comment]
since you created another issue I'll close this one
