### ISSUE TITLE
No module named "raisimpy"

### ISSUE THREAD

**Issue by lok-i** [robotlearn/raisimpy#25]
Hi there
The Installation of raisimLib.raisimOgre was sucessfull and even working flawlessly.
The exact set of commands used for installing raisimpy,

    mkdir build && cd build
    cmake -DPYBIND11_PYTHON_VERSION=3.6.9  
    DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD .. 
    make -j4
    make install

Hence i guess,raisimPy is built properly with pybind 2.4.3,and the final installtion message was,

    [100%] Built target raisimpy
     Install the project...
       -- Install configuration: ""
        -- Installing: /home/lok/Raisim/raisim_build/lib/raisimpy.cpython-36m-x86_64-linux-gnu.so
        -- Set runtime path of "/home/lok/Raisim/raisim_build/lib/raisimpy.cpython-36m-x86_64-linux- 
         gnu.so" to ""

Thus, a file named "raisimpy.cpython-36m-x86_64-linux-gnu.so"  is also made in $LOCAL_BUILD/lib. also in bashrc i have initialized the PYTHONPATH,which i even verfied from within python 3.6.9,

>>> os.environ['PYTHONPATH'].split(os.pathsep)
#output
['/home/lok/Raisim/raisim_build/lib']

Still my python is not able to detect raisimpy as an installed module.Will be really helpful if my mistake is been detected and rectified.

Thanks!!

**Comment by jhwangbo** [comment]
I just tested it with the same python version and it works flawlessly. Which system are you using (OS/hardware)?

**Comment by lok-i** [comment]
> I just tested it with the same python version and it works flawlessly. Which system are you using (OS/hardware)?

os: Ubuntu 18.04
python: 3.6.9

hardware: acer aspire5

but as such have I missed something in the path linking ,or is the installation of pybind wrong or something(as i am still unclear of its role)? Can you once share your bashrc PYTHONPATH variable and extra export statement if any ? do let me know. 

Thanks !

**Comment by lok-i** [comment]
> I just tested it with the same python version and it works flawlessly. Which system are you using (OS/hardware)?

Hi there,
As mentioned earlier raisim,raisimOgre and pybind11 are installed right.
I have followed the exact instructions yet python is not able to detect raisimpy as a module.
These are my exact path variables

    export LOCAL_BUILD="/home/lok/Raisim/raisim_build"
    export PYTHON_VERSION="3.6.9"
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LOCAL_BUILD/lib
    export PYTHONPATH="/home/lok/Raisim/raisim_build/lib"


I am still not able to trace why python is not able to detect.What am I doing wrong here ?

Thanks !

**Comment by jhwangbo** [comment]
can you copy the generated binary right next to the python script?

**Comment by lok-i** [comment]
> can you copy the generated binary right next to the python script?

I copied the python script to the 2 places where the files were built, namely

1. raisimPy/build
2. $LOCAL_BUILD/lib

now the previous error message has gone but there is the same import error in both the above cases. The error goes as below.

    Traceback (most recent call last):
         File "/home/lok/Raisim/raisim_build/lib/anymal.py", line 23, in <module>
           import raisimpy as raisim
       ImportError: libraisimOgre.so: cannot open shared object file: No such file or directory

Even when I call an executable of raisimOgre built using CMake from a python script using **subprocess** module the same error is been printed. What's going wrong?

Thanks!

**Comment by lok-i** [comment]
> can you copy the generated binary right next to the python script?

By binary file you mean the file named like this right?,

    raisimpy.cpython-36m-x86_64-linux-gnu.so

**Comment by lok-i** [comment]
Dear Jemin Hwangbo,
upon calling raisimpy codes from the terminal it is able to run the codes flawlessly, but I had a build system incorporated with the sublime text editor, through which is run the script the errors are still existing. Thanks for the help anyways!

**Comment by jhwangbo** [comment]
oh, that's why you were getting the error... Your sublime is probably not sourcing `.bashrc`. I don't use sublime text editor so I can't tell how it works. For clion, I force it to source `.bashrc` as following
`https://github.com/jhwangbo/raisimHelp/tree/master#how-to-use-variables-defined-in-your-bashrc-in-clion`
