### ISSUE TITLE
SingleBodyObject setExternalForce missing position argument

### ISSUE THREAD

**Issue by srikarg89** [robotlearn/raisimpy#26]
The raisimLib SingleBodyObject class overloads the function setExternalForce with two possible sets of arguments: (localidx, force) and (localidx, pos, force). The raisimpy's SingleBodyObject seems to only have set_external_force defined with the arguments (localidx, force). Is there a reason for this, and if so, is there anyway to apply a force on a specified position on the body?

**Comment by jhwangbo** [comment]
addressed by #27
