### ISSUE TITLE
Jacobian Dimension is wrong in get_dense_linear_jacobian

### ISSUE THREAD

**Issue by xdaumich** [robotlearn/raisimpy#28]
The `get_dense_linear_jacobian` in `articulated_system.cpp` initialize the jacobian with `getGeneralizedCoordinateDim()`. For floating-based, because of the quaternion, the dimension is **7+N**. 

I think the Jacobian is respect to the \dot{q}, whose dimension is **6+N** from from `getDOF`

**Comment by jhwangbo** [comment]
thx for reporting the bug. the fix is pushed
