### ISSUE TITLE
Return Multiple Variables

### ISSUE THREAD

**Issue by xdaumich** [robotlearn/raisimpy#29]
There are a few functions that return two variables, for example, `get_body_pose` returns `position, orientation`. When I run `p, o = robot.get_body_pose(0)`, I get error:

<pre><code>p, o = self.robot.get_body_pose(0)
ValueError: too many values to unpack (expected 2)
</code></pre>

How should I run the code properly? I use pybind11 v2.4.3 and raisimpy 7abf3e37e3050fe18708baddc6382593e8c47061

**Comment by jhwangbo** [comment]
thx for reporting the bug. the fix is pushed
